### ISSUE TITLE
Why doesn't vimtexet recognize math mode between $ $ tags?

### ISSUE THREAD

**Issue by AlekseiSmirnov** [brennier/vimtexer#2] opened 2017-03-08 01:49 UTC
Spent some time trying to realise why vimtexer doesn't work.
It turned out that it recognized math mode only in `\[ \]` environment. Is it possible to recognize for `$ $` tags as well?

Another question - I need to switch language to english each time I'm in math mode and back to Russian once I'm out of math. Is it possiblt to get this behaviour using vimtexer?

**Comment by brennier** [comment] 2017-03-08 03:10
Yes, that is a known limitation that I'm currently trying to figure out. Sorry about the confusion. The problem is that the `$ $` tags are symmetric (and also deprecated, but that's another story), so it's simply more complicated and more computationally expensive to tell if you're in between `$ $` tags. However, I'm actually planning on resolving this issue and on writing a documentation file next week, so this will be fixed very soon.

On a related note, I highly recommend setting up a short keyword to put yourself inside math mode automatically. For example, the default dictionary for tex files has the entry
```vim
let g:vimtexer_tex = {
    \'m' : '\( <+++> \) <++>',
\}
```
which is extremely useful. 

As for you second question, I'm not quite sure what you mean. Do you mean the language that vim uses to display menus? Or do you mean that you want the keywords to be in Russian outside of math mode? If it's the latter, you can set the keywords to be whatever you wish. Using a different character set is not a problem as long as you have vim set up for it.

**Comment by AlekseiSmirnov** [comment] 2017-03-15 15:46
It was a question regarding optimization of vimtex workflow during a development of multilingual LaTex documents.

The problem is that each time I'm in math mode I have to switch from my native language to English in order to add a formula. Currently, I use <C-^> keystroke.

Is it possible to switch language from Russian to English automatically, once I'm in math mode and revert it back to Russian when I leave the math mode?
What is the best way to achieve this behavior?

**Comment by brennier** [comment] 2017-03-15 23:39
I'm still not entirely sure what you mean (the <C-^> key is for switching buffers?), but unfortunately, this program not what you want. Vimtexer checks if you're in math mode every time you press space, and then expands the keyword accordingly. The program doesn't know when you enter or leave math mode.

However, I am glad to say that `$ $` and `$$ $$` are now recognized.

**Comment by AlekseiSmirnov** [comment] 2017-03-16 00:42
I'm sorry for poor explanation. <C-^> is a default key mapping to change input method. You can find more about it by typing `:help iminsert`. Once it's pressed it changes a keymap, so if I have 
`set keymap=russian-jcukenwin` in my .vimrc file, pressing <C-^> will change the input method.

My goal is to change it once I'm in math mode, so I need to have some method that allows me to check if I'm in math mode and automatically switch language to En. 

Found solution in vimtex plugin that has  `vimtex#util#in_mathzone()` method to check if I'm in math mode.

**Comment by AlekseiSmirnov** [comment] 2017-03-16 00:42
Just updated to the last version of vimtexer and it seems that going to <++> after double space doesn't work anymore. 

UPD: realized that after the last commit I should add it to dictionary

**Comment by AlekseiSmirnov** [comment] 2017-03-16 11:33
Just checked recent commit and realized that you also have a method `vimtexer#mathmode#InMathMode()` that returns True if in math mode. Finally, implemented what I wanted. 
If someone will want to have automatic language switch once in math mode here is code snippet for .vimrc file:


```vim
augroup mathmode_toggler
  autocmd!
  autocmd CursorMovedI *.tex call ToggleLangMap()
  autocmd CursorHoldI  *.tex call ToggleLangMap()
  autocmd InsertEnter  *.tex call ToggleLangMap()
  autocmd TextChangedI *.tex call ToggleLangMap()
augroup END

let g:wasru = 2
"0 - if when entered math mode language was english
"1 -  if when entered math mode language was russian
"2 - lang not detected yet
function! ToggleLangMap()
  let l:mathmode = vimtex#util#in_mathzone()
  if l:mathmode == 1 
    "set flag once we entered in math mode
    if g:wasru == 2
      let g:wasru = (&iminsert == 1)
    endif
    "set language to English 
    set iminsert=0
  else   
    "we switch back to language that we had once entered math mode
    if g:wasru==1
        set iminsert=1
        let g:wasru=2
    elseif g:wasru==0
        set iminsert=0
        let g:wasru=2
    endif
  endif
endfunction
```
UPD: updated code as there was a minor bug

**Comment by brennier** [comment] 2017-03-16 16:10
Wow, you are very resourceful. I didn't even realize the vimtex had a function like that. I wondered before if one could use the syntax highlighting to figure out math mode. However, I decided against researching about it because it only works when syntax highlighting is on.

I also want to warn you that the name of this plugin will be changing very soon; the current name is too similar to vimtex. In any case, I'm going to close this thread as it seems that everything has been resolved. And sorry about all the updates without explanation.

**Closed as completed by brennier** 2017-03-16 16:10 UTC

**Comment by AlekseiSmirnov** [comment] 2017-03-16 19:25
> I also want to warn you that the name of this plugin will be changing very soon; the current name is too similar to vimtex.

Thanks for the info.
Yeah, this plugin can be used for many purposes, not necessarily for Tex, so you can even make up not Tex related name

**Comment by brennier** [comment] 2017-03-16 20:44
I wanted to do some tests to see how fast `vimtex#utils#in_mathzone()` was, so I made some modifications to get
```vim
function! in_mathzone()
    return match(map(
                \synstack(line('.'),col('.')-1), 'synIDattr(v:val, ''name'')'),
                \'^texMathZone') >= 0
endfunction
```
and ran some speed tests. It seems that my `vimtexer#mathmode#InMathMode()` function is significantly faster (~5x faster), even though it is much longer. The syntax calls that `in_mathzone()` uses are very slow and also don't work if syntax is off. I thought this might be interesting/useful for you to know.

**Comment by AlekseiSmirnov** [comment] 2017-03-16 22:50
yeah, that's why I use your func. I already noticed that `vimtex#utils#in_mathzone()` doesn't work in a case syntax is off
